### ISSUE TITLE
Alvast wat kleine ideetjes

### ISSUE THREAD

**Issue by tutterstock** [saproto/isaak#3]
Het ziet er tot nu toe al super uit op IOS, ook het icoontje enzo is heel gaaf :) ik heb net de app gedownload en naar de events gekeken net en daar heb ik alvast twee kleine dingetjes over waar je misschien iets mee kan? 
1. Als een activiteit vol is maar je wel staat ingeschreven is het misschien handig om ipv “you cannot sign up” een banner te hebben waarmee je je alsnog kan uitschrijven (ik sta bijvoorbeeld voor weerwolven ingeschreven, die activiteit is vol en ik krijg de “you cannot sign up” melding).
2. Misschien is het ook leuk om net zoals op de site te kunnen zien wie er verder allemaal komen.

**Comment by hesje** [comment]
Dankjewel! :)

Over het eerste puntje heb je zeker gelijk, dat is een foutje in de logica die bepaalt wat er op de knop moet staan. Ga ik mee bezig.

Puntje ben ik het wel mee eens, op dit moment is er nog geen API eindpunt om die data op te vragen. In mijn ogen heeft deze feature geen hoge prioriteit. Het is relatief veel werk voor relatief weinig toegevoegde waarde in mijn ogen. Als ik er tijd voor heb ga ik kijken of we het kunnen implementeren, maar dat wordt niet binnenkort.
